version: "3.8"

services:

  mysql:
    container_name: madbox-mysql-db
    image: mysql:8.0.31
    environment:
      MYSQL_DATABASE: 'madbox'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'madboxer'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'M4db0x3r'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - madbox-mysql-data:/var/lib/mysql

volumes:
  madbox-mysql-data:
